version: '3'

services:
  php:
    build:
      context: .
      args:
        user: ruben
        uid: 1000
    volumes:
      - .:/var/www/ErasmusHelper
    networks:
      - backoffice
    ports:
      - "80:80"
networks:
  backoffice:
    driver: bridge