// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY']!,
    appId: '1:720342091332:android:76e115152a8251b27e5e11',
    messagingSenderId: '720342091332',
    projectId: 'erasmus-helper',
    databaseURL: 'https://erasmus-helper-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'erasmus-helper.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY']!,
    appId: '1:720342091332:ios:2dbec9c7219506227e5e11',
    messagingSenderId: '720342091332',
    projectId: 'erasmus-helper',
    databaseURL: 'https://erasmus-helper-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'erasmus-helper.appspot.com',
    iosClientId: '720342091332-1ufvnvccnsgindjvnp7cgjdc7e0j9gkn.apps.googleusercontent.com',
    iosBundleId: 'com.sumsera.erasmusHelper',
  );
}
